### ISSUE TITLE
Number order doesn't work for DOT as Thousands separator

### ISSUE THREAD

**Issue by hfcipriano** [Teun/thenBy.js#18]
Exist a way to consider dot instead of comma?

**Comment by Teun** [comment]
Maybe you can provide an example of what doesn't work and/or what you would
hope would work?

T

Op 23 aug. 2016 11:22 p.m. schreef "Henrique Cipriano" <
notifications@github.com>:

**Comment by hfcipriano** [comment]
Col number US (after Order DESC)
1,000
2
0.5
that's right
-
Col number PT-BR (after Order DESC)
2
1.000
0,5
that's wrong

**Comment by hfcipriano** [comment]
the thousand separator in PT-BR is DOT. So I believe that ordering always consider the DOT as decimal separator (US Standard)

**Comment by hfcipriano** [comment]
It's happens because I send my back-end data formatted according to the locale. 

I could send unformatted object and use the toLocaleString () to clientSide formatting and leave ThenBy do normal work 

But if there is any way that the ordering consider the locale would be more interesting.

**Comment by Teun** [comment]
Well, I was hoping for some code, but I think I understand where your problem lies. Your data is probably text. Text is ordered alphabetically, so the proper order is (ASC): "0,5", "1.000", "2". You can check this by printing the type:

    console.log(typeof var);

You probably need to first convert your data to numeric. The default function in javascript for this is Number(); So you can do this:

    data.sort(firstBy(function (v) { return Number(v.numberAsText); }));

Now this may not support your localization exactly. However, thenby is a library for combining several orderings into one. Not for parsing strings.

**Comment by Teun** [comment]
There are some good libraries out there to help you parse a string in a certain format to Number. You may want to check http://numeraljs.com/

The other solution (much more light weight and performant) is to fix your strings in your own code. If you know or can influence the format of your data, it should be easy to remove the dots, replce one comma by a dot and make the string the format that javascript expects: decimal literal. http://es5.github.io/#x15.1.2.3
