### ISSUE TITLE
very important

### ISSUE THREAD

**Issue by 374377559** [Teun/thenBy.js#24]
Usually from high to low,An empty string (" ").In general, should be at the bottom,

**Comment by Teun** [comment]
Hi Jack,

A few points of feedback first.
1. It is rather impolite to use the title "very important" to describe your question. It doesn't describe anything about the issue you raise and implies that your issue is more important than others.
2. " " is not an empty string. It is a string containing a space. 
3. When you say "usually" and "in general", you probably mean "according to me", "according to my boss" or "in my culture". These things can be different from place to place.

But lets look at your question. thenBy.js is not a library about sorting orders. It is a library that allows you to combine two orders into one. So for example: first order by name from low to high, then on age high to low. Was is high and what is low is up to you. Most programming languages have some of this built in. In javascript, the default sorting is like this:

    ["a", " " , "",  "b"].sort()
    // returns ["", " ", "a", "b"]

This is because in javascript `(" " < "a")` is `true`.

Now, javascript has two extras for you to customize your sorting. 
1. You can pass in a function to `sort()` that knows what should come above what.
2. Modern browsers implement a method on String called localeCompare. This also knows about sorting orders in certain languages (like in German where ä should come right after a). Check it out: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare 

Finally, if the normal sorting of javascript is fine, but you only want empty strings sorted at the end, you can Google how to do that. You'll find this: https://stackoverflow.com/questions/33016087/js-sort-empty-to-end

ThenBy will not be modified into supporting all kinds of specific sortings. It is only about combining sortings.

Last remark: if I do what you say: sorting from high to low using thenBy, the spaces and empties DO come at the end. Check here: https://jsfiddle.net/jtpkwycu/
